"""create application tables

Revision ID: dba1d7b190d5
Revises: 0001_enable_extensions
Create Date: 2026-09-07 21:29:25.012845
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# Needed so autogenerated Vector columns resolve at migration time.
import pgvector.sqlalchemy  # noqa: F401

revision: str = 'dba1d7b190d5'
down_revision: str | None = '0001_enable_extensions'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('preferred_language', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('artisan_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('state_code', sqlmodel.sql.sqltypes.AutoString(length=4), nullable=False),
    sa.Column('district', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=True),
    sa.Column('cluster', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=True),
    sa.Column('craft', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=True),
    sa.Column('scheme', sa.String(), nullable=False),
    sa.Column('beneficiary_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('beneficiary_verified', sa.Boolean(), nullable=False),
    sa.Column('intake_monthly_income', sa.Integer(), nullable=True),
    sa.Column('bio', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('profile_image_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verification_document_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artisan_profiles_beneficiary_id'), 'artisan_profiles', ['beneficiary_id'], unique=False)
    op.create_index(op.f('ix_artisan_profiles_is_verified'), 'artisan_profiles', ['is_verified'], unique=False)
    op.create_index(op.f('ix_artisan_profiles_scheme'), 'artisan_profiles', ['scheme'], unique=False)
    op.create_index(op.f('ix_artisan_profiles_state_code'), 'artisan_profiles', ['state_code'], unique=False)
    op.create_index(op.f('ix_artisan_profiles_user_id'), 'artisan_profiles', ['user_id'], unique=True)
    op.create_table('products',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('artisan_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('title_en', sqlmodel.sql.sqltypes.AutoString(length=160), nullable=True),
    sa.Column('title_hi', sqlmodel.sql.sqltypes.AutoString(length=160), nullable=True),
    sa.Column('description_en', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description_hi', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=60), nullable=True),
    sa.Column('material', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('technique', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('state_code', sqlmodel.sql.sqltypes.AutoString(length=4), nullable=True),
    sa.Column('sku', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('stock_quantity', sa.Integer(), nullable=False),
    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('minimum_order_quantity', sa.Integer(), nullable=False),
    sa.Column('is_made_to_order', sa.Boolean(), nullable=False),
    sa.Column('hours_of_work', sa.Float(), nullable=True),
    sa.Column('material_cost', sa.Integer(), nullable=True),
    sa.Column('price_floor', sa.Integer(), nullable=True),
    sa.Column('price_p10', sa.Integer(), nullable=True),
    sa.Column('price_p50', sa.Integer(), nullable=True),
    sa.Column('price_p90', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('source_name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('source_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_license', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('is_demo_data', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['artisan_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_artisan_id'), 'products', ['artisan_id'], unique=False)
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index(op.f('ix_products_client_id'), 'products', ['client_id'], unique=True)
    op.create_index(op.f('ix_products_is_demo_data'), 'products', ['is_demo_data'], unique=False)
    op.create_index(op.f('ix_products_state_code'), 'products', ['state_code'], unique=False)
    op.create_index(op.f('ix_products_status'), 'products', ['status'], unique=False)
    op.create_table('craft_passports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('artisan_id', sa.Uuid(), nullable=False),
    sa.Column('payload_b64', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
    sa.Column('signature_b64', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('public_key_hex', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('scan_count', sa.Integer(), nullable=False),
    sa.Column('last_scanned_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['artisan_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_craft_passports_artisan_id'), 'craft_passports', ['artisan_id'], unique=False)
    op.create_index(op.f('ix_craft_passports_product_id'), 'craft_passports', ['product_id'], unique=True)
    op.create_table('product_images',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('original_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('cutout_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('enhanced_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('source_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('attribution', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_images_product_id'), 'product_images', ['product_id'], unique=False)
    op.create_table('passport_scans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('passport_id', sa.Uuid(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('scanned_at', sa.DateTime(), nullable=False),
    sa.Column('country_code', sqlmodel.sql.sqltypes.AutoString(length=4), nullable=True),
    sa.Column('state_code', sqlmodel.sql.sqltypes.AutoString(length=4), nullable=True),
    sa.Column('referrer', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['passport_id'], ['craft_passports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_passport_scans_passport_id'), 'passport_scans', ['passport_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_passport_scans_passport_id'), table_name='passport_scans')
    op.drop_table('passport_scans')
    op.drop_index(op.f('ix_product_images_product_id'), table_name='product_images')
    op.drop_table('product_images')
    op.drop_index(op.f('ix_craft_passports_product_id'), table_name='craft_passports')
    op.drop_index(op.f('ix_craft_passports_artisan_id'), table_name='craft_passports')
    op.drop_table('craft_passports')
    op.drop_index(op.f('ix_products_status'), table_name='products')
    op.drop_index(op.f('ix_products_state_code'), table_name='products')
    op.drop_index(op.f('ix_products_is_demo_data'), table_name='products')
    op.drop_index(op.f('ix_products_client_id'), table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_index(op.f('ix_products_artisan_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_artisan_profiles_user_id'), table_name='artisan_profiles')
    op.drop_index(op.f('ix_artisan_profiles_state_code'), table_name='artisan_profiles')
    op.drop_index(op.f('ix_artisan_profiles_scheme'), table_name='artisan_profiles')
    op.drop_index(op.f('ix_artisan_profiles_is_verified'), table_name='artisan_profiles')
    op.drop_index(op.f('ix_artisan_profiles_beneficiary_id'), table_name='artisan_profiles')
    op.drop_table('artisan_profiles')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
