"""Alembic environment.

Two things here that are easy to get wrong and painful to debug:

1. The vector extension has to exist before any table using it, so the first
   migration creates it. Autogenerate will never add that line itself.
2. Autogenerate cannot reflect pgvector's Vector type, so it is registered on
   the dialect below. Without this, every autogenerated migration silently
   drops the embedding columns.
"""

from logging.config import fileConfig

from alembic import context
from sqlalchemy import engine_from_config, pool
from sqlmodel import SQLModel

import app.models  # noqa: F401 - importing registers every table
from app.core.config import settings

config = context.config
# configparser treats % as interpolation syntax, and the Supabase password is
# percent encoded, so passing the URL straight through makes every alembic
# command die before it connects. Doubling the signs escapes them.
config.set_main_option("sqlalchemy.url", settings.DATABASE_URL.replace("%", "%%"))

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = SQLModel.metadata


def _register_vector(connection) -> None:
    try:
        import pgvector.sqlalchemy

        connection.dialect.ischema_names["vector"] = pgvector.sqlalchemy.Vector
    except ImportError:
        pass


def run_migrations_offline() -> None:
    context.configure(
        url=settings.DATABASE_URL,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        compare_type=True,
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        _register_vector(connection)
        context.configure(
            connection=connection, target_metadata=target_metadata, compare_type=True
        )
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
